version: '3.8'

services:
  # Serviço do Backend
  backend:
    build: ./BackendJ
    container_name: espike-backend
    restart: unless-stopped
    ports:
      - "5174:5174" # Mapeia a porta 5174 do seu PC para a 5174 do contêiner
    environment:
      - MONGO_URI=mongodb://mongo:27017/espike_db
    networks:
      - espike-net

  # Serviço do Frontend
  frontend:
    build: ./Frontend
    container_name: espike-frontend
    restart: unless-stopped
    ports:
      - "5173:80" # Mapeia a porta 5173 do seu PC para a 80 do contêiner Nginx
    depends_on:
      - backend
    networks:
      - espike-net

  # Serviço do Banco de Dados
  mongo:
    image: mongo:latest
    container_name: espike-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - espike-net

networks:
  espike-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local