name: Teste de Build (Frontend e Backend)

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
#teste
jobs:
  build-frontend:
    name: Build do Frontend (Vue.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências e Build do Frontend
        working-directory: ./Frontend
        run: |
          npm install --force
          npm run build

  build-backend:
    name: Build do Backend (Node.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar Dependências do Backend
        working-directory: ./BackendJ
        run: npm install
